version: '3.7'

services:
  backend:
    container_name: ComponantStockAPI
    build: .
    ports:
    - "50001:50001"
    volumes:
    - .:/app
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ComponentStock
    ports:
    - "27017:27017"
    volumes:
      - .:/app/ComponentStock
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:1.0.0-20
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
