name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Print MongoDB Credentials
        run: |
          echo "MongoDB Username: ${{ secrets.MONGO_USERNAME }}"
          echo "MongoDB Password: ${{ secrets.MONGO_PASSWORD }}"

      - name: Test MongoDB Connection
        run: |
          mongo --username ${{ secrets.MONGO_USERNAME }} --password ${{ secrets.MONGO_PASSWORD }} --eval 'db.runCommand({ connectionStatus: 1 })'

      - name: Run tests
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          MONGO_DB: ComponentStockTesting
        run: |
          python -m unittest discover tests/