name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [ '4.0', '4.2', '4.4' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start MongoDB
          uses: MongoCamp/mongodb-github-action@1.0.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}
            mongodb-username: ${{ secrets.MONGO_USERNAME }}
            mongodb-pwd: ${{ secrets.MONGO_PASSWORD }}

            - run: curl http://localhost:27017

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          MONGO_DB: ComponentStockTesting
        run: |
          python -m unittest discover tests/