name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.10.0
          with:
            mongodb-version: 4.2
            mongodb-username: ${{ secrets.MONGO_USERNAME }}
            mongodb-password: ${{ secrets.MONGO_PASSWORD }}
            mongodb-db: ComponentStockTesting
            mongodb-port: 27017

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          MONGO_DB: ComponentStockTesting
        run: |
          python -m unittest discover tests/